milo_django_task/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('users:index'))),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new_user, name='new'),
    url(r'^edit/(?P<user_id>[0-9]+)/$', views.edit_user, name='edit'),
    url(r'^delete/(?P<user_id>[0-9]+)/$', views.delete_user, name='delete'),
    url(r'^download/$', views.download, name='download'),
]

users/models.py
from __future__ import unicode_literals
import random
from datetime import date

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator


class CustomUser(AbstractUser):
    date_of_birth = models.DateField(default=date.today)
    random = models.IntegerField(
        default=lambda: random.randint(1, 100),
        validators=[
            MinValueValidator(1),
            MaxValueValidator(100)
        ])

users/forms.py
from django.forms import ModelForm, widgets
from .models import CustomUser


class NewUserForm(ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'date_of_birth')

        widgets = {
            'username': widgets.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Username'}),

            'first_name': widgets.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'First name'}),

            'last_name': widgets.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Last name'}),

            'email': widgets.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'Email'}),

            'date_of_birth': widgets.DateInput(
                format='%Y-%m-%d', attrs={'class': 'form-control'})
        }


class EditUserForm(NewUserForm):

    class Meta(NewUserForm.Meta):
        exclude = ('username',)

users/views.py
import csv
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from .models import CustomUser
from .forms import NewUserForm, EditUserForm


def index(request):
    users = CustomUser.objects.all()
    return render(request, 'users/index.html', {'users': users})


def new_user(request):

    if request.method == 'GET':
        return render(request, 'users/new.html', {'form': NewUserForm()})

    elif request.method == 'POST':

        form = NewUserForm(request.POST)

        if not form.is_valid():
            return render(request, 'users/new.html', {'form': form})

        form.save()
        return redirect(reverse('users:index'))


def edit_user(request, user_id):

    user = get_object_or_404(CustomUser, pk=user_id)

    if request.method == 'GET':

        form = EditUserForm(instance=user)
        return render(request, 'users/edit.html', {'form': form, 'user': user})

    elif request.method == 'POST':

        form = EditUserForm(request.POST, instance=user)

        if not form.is_valid():
            return render(request, 'users/edit.html',
                          {'form': form, 'user': user})

        form.save()
        return redirect(reverse('users:index'))


def delete_user(request, user_id):

    user = get_object_or_404(CustomUser, pk=user_id)

    if request.method == 'GET':
        return render(request, 'users/confirm_delete.html', {'user': user})

    elif request.method == 'POST':

        user.delete()
        return redirect(reverse('users:index'))


def download(request):

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'

    writer = csv.writer(response)

    fields = ('username', 'first_name', 'last_name', 'email', 'date_of_birth')

    for user in CustomUser.objects.all():

        row = []

        for f in fields:
            if f == 'date_of_birth':
                row.append(getattr(user, f).strftime('%Y-%m-%d'))
            else:
                row.append(getattr(user, f))

        writer.writerow(row)

    return response

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> CustomUsers App </title>

        <meta http-equiv="X-UA-Compatible" content="chrome=IE7" />

        <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">

    </head>
    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

users/templates/users/confirm_delete.html
{% extends "users/base.html" %}

{% block content %}

<div class="container">
<br/>
<br/>

<form action="{% url 'users:delete' user.id %}" method="post">{% csrf_token %}
    <p>Are you sure you want to delete user "{{ user.username }}" ?</p>
    <input type="submit" value="Confirm" />
</form>


</div>

{% endblock %}

users/templates/users/edit.html
{% extends "users/base.html" %}

{% block content %}
<script>
  $(function() {
    $('#id_date_of_birth').datepicker({
        dateFormat: "yy-mm-dd",
        changeYear: true,
        yearRange: "-100:+0"
    });
  });
</script>

<div class="container">
<br/>
<br/>
<a href="{% url 'users:index' %}">Main</a> -&gt; <a href="{% url 'users:edit' user.id %}">Edit</a>

<h2>Edit User</h2>
<br/>

<form action="{% url 'users:edit' user.id %}" method="post" class="form-horizontal">

    {% csrf_token %}

    <div class="form-group">
        <label class="col-sm-2 control-label">Username</label>
        <div class="col-sm-10">
            {{ user.username }}
        </div>
    </div>

    {% for field in form %}
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
            <div class="col-sm-10">
                {{ field }}
                {{ field.errors }}
            </div>
        </div>
    {% endfor %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

</div>
{% endblock %}

users/templates/users/index.html
{% extends "users/base.html" %}
{% load extras %}

{% block content %}
<div class="container">

<h2>List of Users</h2>
<br/>

{% if users %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Username</th>
            <th>Birthday</th>
            <th>Eligible</th>
            <th>Random Number</th>
            <th>BizzFuzz</th>
            <th>Actions</th>
        </tr>
    </thead>

    {% for user in users %}
    <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.date_of_birth }}</td>
        <td>{% Eligible user %}</td>
        <td>{{ user.random }}</td>
        <td>{% BizzFuzz user %}</td>

        <td>
            <div align="center">
                <a href="{% url 'users:edit' user.id %}" title="Edit this record">Edit</a>
                    &nbsp; | &nbsp;
                <a href="{% url 'users:delete' user.id %}" title="Delete this record">Delete</a>
            </div>
        </td>
    </tr>
    {% endfor %}

</table>

{% else %}
    <p> users not found </p>
{% endif %}

<a href="{% url 'users:new' %}">New</a> | <a href="{% url 'users:download' %}">Download CSV</a>
</div>

{% endblock %}

users/templates/users/new.html
{% extends "users/base.html" %}

{% block content %}
<script>
  $(function() {
    $('#id_date_of_birth').datepicker({
        dateFormat: "yy-mm-dd",
        changeYear: true,
        yearRange: "-100:+0"
    });
  });
</script>

<div class="container">
<br/>
<br/>
<a href="{% url 'users:index' %}">Main</a> -&gt; <a href="{% url 'users:new' %}">New</a>

<h2>Add New User</h2>
<br/>

<form action="{% url 'users:new' %}" method="post" class="form-horizontal">

    {% csrf_token %}

    {% for field in form %}
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
            <div class="col-sm-10">
                {{ field }}
                {{ field.errors }}
            </div>
        </div>
    {% endfor %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>

</form>

</div>
{% endblock %}